################################################################################
# Laravel Cloud Deployment Configuration
# https://cloud.laravel.com/docs
################################################################################

# Build Configuration
build:
  # Install Node dependencies and build assets
  - npm ci
  - npm run build

  # Install PHP dependencies
  - composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

# Deployment Commands
deploy:
  # Clear all caches to prevent stale/corrupted views
  - php artisan view:clear
  - php artisan config:clear
  - php artisan route:clear
  - php artisan cache:clear

  # Run database migrations
  - php artisan migrate --force

  # Optimize application for production
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache
  - php artisan event:cache

  # Storage link (if needed)
  - php artisan storage:link || true

  # Queue restart (if using queues)
  - php artisan queue:restart || true

# Environment Variables
# These are defined in the Laravel Cloud dashboard
# Just documenting what's needed here:
# - APP_ENV=production
# - APP_DEBUG=false
# - APP_KEY=<your-key>
# - DB_CONNECTION=mysql
# - DB_HOST=<host>
# - DB_DATABASE=<database>
# - DB_USERNAME=<username>
# - DB_PASSWORD=<password>

# Health Check
# Laravel Cloud will ping this endpoint to verify deployment
health:
  path: /

# Scheduled Tasks (Cron Jobs)
# Uncomment if you use Laravel's task scheduler
# schedule:
#   - command: php artisan schedule:run
#     frequency: "* * * * *"

# Queues Configuration
# Uncomment if you use queues
# queues:
#   - name: default
#     connection: redis
#     processes: 3
#     tries: 3
#     timeout: 60
